### ISSUE TITLE
[Bug]: tree shaking breaks with require() in some situation

### ISSUE THREAD

**Issue by Ayc0** [web-infra-dev/rspack#11226]
### System Info

```
  System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.34 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.4.1 - ~/.volta/tools/image/node/24.4.1/bin/node
    Yarn: 1.22.22 - ~/.volta/tools/image/yarn/1.22.22/bin/yarn
    npm: 11.4.2 - ~/.volta/tools/image/node/24.4.1/bin/npm
    pnpm: 10.13.1 - ~/.volta/tools/image/pnpm/10.13.1/bin/pnpm
    bun: 1.2.19 - /opt/homebrew/bin/bun
    Watchman: 2025.07.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 135.1.77.97
    Chrome: 138.0.7204.169
    Chrome Canary: 140.0.7326.0
    Firefox Nightly: 141.0a1
    Safari: 18.5
  npmPackages:
    @rspack/core: ^1.4.10 => 1.4.10
```

### Details

If you have a file `foo.ts` that contains 2 exports:

```ts
// foo.ts
exports.bar = 'bar';
exports.paz = 'paz';
```

Tree shaking will work (aka the unused variable will be stripped out during compilation) when writing:

```ts
// stripped.ts
import { bar } from './foo';
const bar = require('./foo').bar;
```

But in some other instances, `paz` is kept in the bundle:

```ts
// kept.ts
const { bar } = require('./foo');
const module = require('./foo'); // And then only `module.foo` is used
```

### Reproduce link

https://github.com/Ayc0/code-splitting-issue

### Reproduce Steps

You can clone https://github.com/Ayc0/code-splitting-issue and run `node --test tests/rspack.test.mjs` (requires node 24.4.0+)

**Comment by ahabhgk** [comment]
Should resolved by:

- https://github.com/web-infra-dev/rspack/pull/13155
- https://github.com/web-infra-dev/rspack/pull/13149

**Comment by Ayc0** [comment]
@ahabhgk do you know if this requires specific config?

Those tests here are still failing: https://github.com/Ayc0/code-splitting-issue/blob/23a13843d6f61817d31b5f5227d39ed94323ae68/tests/rspack.test.mjs#L63-L73

And I'm on the latest `@rspack/core` I believe

**Comment by ahabhgk** [comment]
No config needed, this feature is actually released in v2: [2.0.0-beta.7](https://www.npmjs.com/package/@rspack/core/v/2.0.0-beta.7)

**Comment by Ayc0** [comment]
Ohhh, that makes sense!

Let me try it 👀

**Comment by Ayc0** [comment]
It worked!

Thank you 🙇
