### ISSUE TITLE
when optimization.moduleIds =  'named',  an absolute-path module identifier makes error in windows file system.

### ISSUE THREAD

**Issue by aliveornot** [web-infra-dev/rspack#2988]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 16.10 GB / 31.93 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.64)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rspack/cli: latest => 0.1.9

### Details

If you set `optimization.moduleIds` to be `'named'`, it is expected that bundled modules have identifiers that resemble the original file path. 

- If the module can be imported from a relative path, it works just fine. But if the module must be imported from an absolute path, (i.e. the module is imported from a different drive), the module identifier breaks in windows file system, because it uses `\` instead of `\\`.

- Webpack seems to handle it well, and I included a snapshot to show that. 
  (I imported a module named `simple-demo-package` from another drive, and compiled it with RsPack and WebPack, respectively.)

![image](https://user-images.githubusercontent.com/60848153/235337632-aca556e9-de94-45eb-9784-b2bfae314ea7.png)

### Reproduce link

https://github.com/aliveornot/rspack-module-id-bug

### Reproduce Steps

> Clone the repo into a drive.

1. clone the repo, into a windows machine that has at least two different drives. (let's say you cloned into `d:/src/rspack-bug`)

> Make another project in a different drive.
2. Initialize another npm project somewhere like `c:/src/rspack-bug-2`
3. install `simple-demo-package` by `yarn add simple-demo-package`

> Modify rspack.config.js accordingly.
4. open rspack.config.js in the cloned project from (1)
5. modify `resolve.modules` so that it imports from project initilized in (2)
6. run `yarn build`

Now, open `./dist/main.js` and you can see the imported module name contains single-backslash. It's especially erroneous when the name of the package starts with u, because it makes the module identifier contain `\u****`, which is a unicode escape sequence.

**Comment by hardfist** [comment]
should be fixed by #3220

**Comment by aliveornot** [comment]
Thanks a lot!

**Comment by aliveornot** [comment]
Oh I checked with somewhat more complicate repo which I'm actually working on, and the bug persists in some cases. Please take a look at #3306

**Comment by hardfist** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/8898718/d2e34f55-89c9-4e5f-9b1c-bf8ed9a8ed1e)

@alexander-akait sorry to bother you again, do you know why webpack don't use normalize path when dealing with cross driver path?

**Comment by hardfist** [comment]
if it is out of context，why cant we use path like ”../../../other-folder/lib.js”

**Comment by alexander-akait** [comment]
You can, but loader should do it on own side when inject `import()` or plugins, i.e. contextify
