### ISSUE TITLE
split chunks sometime doesn't work

### ISSUE THREAD

**Issue by tjx666** [web-infra-dev/rspack#5485]
### System Info

```node
 System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 955.63 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 121.0.6167.85
    Edge: 120.0.2210.144
    Safari: 17.2.1
  npmPackages:
    @rsdoctor/webpack-plugin: ^0.1.0 => 0.1.0 

```
 
### Details

With following split chunk config, sometimes will generate `lib.js`, sometimes not

```javascript
splitChunks: {
    cacheGroups: {
        // when use with rsdoctor, will not generate this chunk
        lib: {
            test: /[/\\]node_modules[/\\](react|react-dom|antd)[/\\]/,
            name: 'lib',
            chunks: 'all',
        },
        vendor: {
            test: /[/\\]node_modules[/\\]/,
            name: 'vendor',
            chunks: 'all',
        },
    },
}
```

https://github.com/web-infra-dev/rspack/assets/41773861/38c25f21-2d5d-4bf0-9b8b-9b50ba1646fc

### Reproduce link

https://github.com/tjx666/react-rspack-boilerplate

### Reproduce Steps

1. git clone git@github.com:tjx666/react-rspack-boilerplate.git
2. git checkout af99a4a703eec21eea48705c6c1f1cbde21d688f
3. pnpm install
4. pnpm build
5. `remove -rf ./dist && pnpm build` multiple time to checkout the dist

**Comment by JSerFeng** [comment]
Thanks for reporting. Fixed by #5488

If you want to have lib chunk generated, please set priority to it, and make sure it's higher than vendor priority

**Comment by tjx666** [comment]
Seems still doesn't work with builtin `rspack.HtmlRspackPlugin`.

checkout the reproduce repository to hash `f9b589d125655652ea6156d414a0c06068b1aebc` can reproduce.
