### ISSUE TITLE
[Bug]: imported default values not working for classes in 0.6.1

### ISSUE THREAD

**Issue by tobua** [web-infra-dev/rspack#6244]
### System Info

System:
    OS: macOS
  Binaries:
    Node: 21.7.3 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
    bun: 1.1.3 - ~/.bun/bin/bun
  npmPackages:
    @rspack/cli: 0.6.1 => 0.6.1 
    @rspack/core: 0.6.1 => 0.6.1 
    @rspack/plugin-react-refresh: 0.6.1 => 0.6.1 

### Details

This seems like a bundler issue but I'm not sure:

```js
// util.js: export const value = "GET";
import { value } from "./util";

class Store {
  constructor(first, second, third = value) {
    console.log(first, second, third);
  }
}

function regularFunction(first, second, third = value) {
  console.log(first, second, third);
}

console.log(regularFunction("this", "works"));
console.log(new Store("this", "fails"));
```

Default values will not work when used in class constructors. Hardcoded values as well as regular functions work fine and as far as I know this should work. It's for example used in the [workbox](https://github.com/GoogleChrome/workbox/blob/b950cd67a7d311bac4e47b0895724ba79243eac6/packages/workbox-routing/src/Route.ts#L48) package.

Is this a bug?

### Reproduce Steps

1) Run above code with rspack-cli
2) Will error in constructor as value does not exist

**Comment by sfc-gh-jdaly** [comment]
See:
https://github.com/web-infra-dev/rspack/issues/6230
https://github.com/web-infra-dev/rspack/issues/6213
https://github.com/web-infra-dev/rspack/issues/6197

This should be fixed in canary

**Comment by tobua** [comment]
Thanks for the info, closing this as it will be fixed with the next release in https://github.com/web-infra-dev/rspack/pull/6198

**Comment by tobua** [comment]
The mentioned pull request has already been released with https://github.com/web-infra-dev/rspack/pull/6198 in 0.6.1 and the issue persists. So I'm reopening this.

**Comment by tobua** [comment]
Nevermind, it's fine in canary, 0.6.1 has been released 5 days ago, it's just the release notes which mentioned a similar fix have only been published yesterday.
