### ISSUE TITLE
[Bug] Invalid fallback `"javascript/auto"` rule.type passed to getRawGeneratorOptions

### ISSUE THREAD

**Issue by omonk** [web-infra-dev/rspack#6873]
https://github.com/web-infra-dev/rspack/blob/d73b4fa2ad3dc4740cd7db2bf9b133443a046639/packages/rspack/src/config/adapter.ts#L444

The default `type` argument is `"javascript/auto"` which throws an error during build as there is no condition which matches 

```
Error: unreachable: unknow module type: javascript/auto
```

https://github.com/web-infra-dev/rspack/blob/d73b4fa2ad3dc4740cd7db2bf9b133443a046639/packages/rspack/src/config/adapter.ts#L683-L728

**Comment by xc2** [comment]
Are you passing an empty generator config to a rule item?

**Comment by ahabhgk** [comment]
This should be fixed by https://github.com/web-infra-dev/rspack/pull/6997/files#diff-5f5bb1aeb2a977ff30c5ab822c79f09b76476c503462939c69beb9e4d7552123, which will be released in 1.0.0-alpha.1

**Comment by ahabhgk** [comment]
Feel free to re-open if it still exists in v1.0.0-alpha.1

**Comment by 9aoy** [comment]
It seems that it just avoids using `javascript/auto` as the default value. When I manually set the type to `javascript/auto` in rspack v1.0.0-alpha.3, I still encounter this error.

<img width="834" alt="image" src="https://github.com/user-attachments/assets/933c2396-ac40-4a78-99d1-ac96773290a2">


According to the introduction of webpack, when the type is javascript/auto, it seems that it should be ignored instead of reporting an error. [see](https://webpack.js.org/configuration/module/#modulegenerator)

<img width="671" alt="image" src="https://github.com/user-attachments/assets/d33f03a9-2e47-4bd0-99ee-c37ce89dd768">
