### ISSUE TITLE
RSPack Fails on iOS 16 / Older Safari Versions With "Duplicate Parameter `e` Not Allowed In Function With Default Parameters"

### ISSUE THREAD

**Issue by mfranzs** [web-infra-dev/rspack#7034]
### System Info

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 152.30 MB / 16.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 3.3.0 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Brave Browser: 111.1.49.128
    Chrome: 126.0.6478.127
    Edge: 121.0.2277.128
    Firefox: 125.0.3
    Safari: 17.0

### Details

On iOS 16 (which still has 30%+ iOS market share) and older versions of Safari, we're running into this issue: 

> "Duplicate Parameter `e` Not Allowed In Function With Default Parameters"
![CleanShot 2024-07-03 at 16 22 51@2x](https://github.com/web-infra-dev/rspack/assets/953103/9a08affa-5377-494a-956d-70c28532fa91)

My guess is that older version of Webkit seems to fail with code like this:
```
function a(e) { // RSPack's module definition
  function b(e) { // A function in our module. This incorrectly also has the variable name `e` here. Normally this is fine, but this causes problems on iOS 16.
     // String templating then triggers the webkit bug:
     console.log(`Hello{$e}`);
   }
}
```

On webpack this code equivalently compiles to: 
![CleanShot 2024-07-03 at 16 23 58@2x](https://github.com/web-infra-dev/rspack/assets/953103/5f290460-b641-4a42-a637-0126ac843507)

Note how on Webpack, the variables are different, which avoids this issue.

This only happens when minification is on, on our production build, which makes this very thorny. We're using the default `minimize: true` option (which from my understanding is using SwcJsMinimizerRspackPlugin underneath).

Do you know how we can fix this or avoid this issue? For example, do you know how to achieve any of these workarounds?
- Is there some way that we could force the name of the module variables here to some fixed non-overlapping values? 
- We tried setting `mangle.reserved: ['e']`, but then the variable in both functions changed to `t`.
- Is there some config that will pollyfil string templates? (Babel has something that will convert `A{$B}` to `"A" + B`)

Many thanks for any help in advance, and thanks for creating rspack!

### Reproduce Steps

Despite a lot of effort, we unfortunately haven't been able to find a minimal reproduction yet. I'm not sure why - I think we might be misunderstanding the exact situation that causes this somehow. 

However, I'm confident that we've identified the correct problem in our repo - when we remove the offending lines, the error goes away. Unfortunately, we rely on a lot of npm packages that also use string templating, and have no way to remove the bad string templates from them.

**Comment by markmssd** [comment]
We ran in a similar issue in the past after upgrading SWC, using Webpack. We fixed it with those minimizer options:

```
  mangle: {
    toplevel: false,

    // Needed to prevent Safari bug
    // https://bugs.webkit.org/show_bug.cgi?id=220517
    keepFnNames: true,
  },
```

**Comment by mfranzs** [comment]
@markmssd Wow, thank you so much - it worked! You saved me a huge amount of further headache - thank you!

For others:
```
 minimizer: [
        new rspack.SwcJsMinimizerRspackPlugin({
          mangle: {
            // Needed to prevent Safari bug
            // https://bugs.webkit.org/show_bug.cgi?id=220517
            keep_fnames: true,
          },
          compress: {
            // Needed to prevent Safari bug
            // https://bugs.webkit.org/show_bug.cgi?id=220517
            keep_fnames: true,
          },
        }),
        new rspack.SwcCssMinimizerRspackPlugin(),
      ],
```

Inspecting the output, I still see the duplicate `e` there. Maybe I misdiagnosed the problem? I don't understand why this solution worked, to be honest. 
![CleanShot 2024-07-03 at 17 01 27@2x](https://github.com/web-infra-dev/rspack/assets/953103/71d12471-3d0d-4af5-af08-5c90727e2fb1)


I'll leave this open so that the core issue can hopefully be fixed.

**Comment by markmssd** [comment]
Awesome glad I could help! Btw in our case, using the option in `mangle` only was enough (not in `compress`). Was it still failing for you if you didn't put it in compress?

**Comment by h-a-n-a** [comment]
Looks like the issue is resolved. ;-)

**Comment by mfranzs** [comment]
@h-a-n-a I don't think this should be closed - the default behavior here is a bug IMO, and I expect that other projects using rspack will run into this issue on iOS 16 (which still has 30%+ mobile market share). It's a reasonably serious issue as the entire bundle will fail to load, and it's quite hard to debug. 

(Thank you for rspack by the way!)

**Comment by GiancarlosIO** [comment]
Just got this error this morning. Would be good to re-open to see if it can be fixed by default in the rspack side 🙏🏼

**Comment by williamstein** [comment]
This bug is still very much present today and it seems like it should be re-opened.  The workarounds mentioned above need to be changed as follows:

```
config = {
     ...

    optimization: {
      minimizer: [
        // See https://github.com/web-infra-dev/rspack/issues/7034
        new SwcJsMinimizerRspackPlugin({
          minimizerOptions: {
            mangle: {
              // Needed to prevent Safari bug
              // https://bugs.webkit.org/show_bug.cgi?id=220517
              keep_fnames: true,
            },
            compress: {
              // Needed to prevent Safari bug
              // https://bugs.webkit.org/show_bug.cgi?id=220517
              keep_fnames: true,
            },
          },
        }),
      ],
    },
  };
```

(I'm a superfan of rspack -- many thanks for one of the most incredible pieces of software ever!)

**Comment by hardfist** [comment]
> This bug is still very much present today and it seems like it should be re-opened. The workarounds mentioned above need to be changed as follows:
> 
> ```
> config = {
>      ...
> 
>     optimization: {
>       minimizer: [
>         // See https://github.com/web-infra-dev/rspack/issues/7034
>         new SwcJsMinimizerRspackPlugin({
>           minimizerOptions: {
>             mangle: {
>               // Needed to prevent Safari bug
>               // https://bugs.webkit.org/show_bug.cgi?id=220517
>               keep_fnames: true,
>             },
>             compress: {
>               // Needed to prevent Safari bug
>               // https://bugs.webkit.org/show_bug.cgi?id=220517
>               keep_fnames: true,
>             },
>           },
>         }),
>       ],
>     },
>   };
> ```
> 
> (I'm a superfan of rspack -- many thanks for one of the most incredible pieces of software ever!)

it seems it's also the default behavior of webpack minifier(terser-webpack-plugin)

**Comment by soapwong703** [comment]
I have just encountered this issue and resolved by updating to latest rsbuild/rspack version.  Seems it is already fixed in the latest version?

**Comment by williamstein** [comment]
It looks like the upstream Safari bug this was working around was fixed in Oct 2023, so the workaround is presumably no longer needed.
